# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /e/Projects/texel-tuner-main/texel-tuner-main/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /e/Projects/texel-tuner-main/texel-tuner-main/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /e/Projects/texel-tuner-main/texel-tuner-main/src/CMakeFiles /e/Projects/texel-tuner-main/texel-tuner-main/src//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /e/Projects/texel-tuner-main/texel-tuner-main/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tuner

# Build rule for target.
tuner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tuner
.PHONY : tuner

# fast build rule for target.
tuner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/build
.PHONY : tuner/fast

engines/rice.o: engines/rice.cpp.o
.PHONY : engines/rice.o

# target to build an object file
engines/rice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/engines/rice.cpp.o
.PHONY : engines/rice.cpp.o

engines/rice.i: engines/rice.cpp.i
.PHONY : engines/rice.i

# target to preprocess a source file
engines/rice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/engines/rice.cpp.i
.PHONY : engines/rice.cpp.i

engines/rice.s: engines/rice.cpp.s
.PHONY : engines/rice.s

# target to generate assembly for a file
engines/rice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/engines/rice.cpp.s
.PHONY : engines/rice.cpp.s

engines/toy.o: engines/toy.cpp.o
.PHONY : engines/toy.o

# target to build an object file
engines/toy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/engines/toy.cpp.o
.PHONY : engines/toy.cpp.o

engines/toy.i: engines/toy.cpp.i
.PHONY : engines/toy.i

# target to preprocess a source file
engines/toy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/engines/toy.cpp.i
.PHONY : engines/toy.cpp.i

engines/toy.s: engines/toy.cpp.s
.PHONY : engines/toy.s

# target to generate assembly for a file
engines/toy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/engines/toy.cpp.s
.PHONY : engines/toy.cpp.s

engines/toy_tapered.o: engines/toy_tapered.cpp.o
.PHONY : engines/toy_tapered.o

# target to build an object file
engines/toy_tapered.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/engines/toy_tapered.cpp.o
.PHONY : engines/toy_tapered.cpp.o

engines/toy_tapered.i: engines/toy_tapered.cpp.i
.PHONY : engines/toy_tapered.i

# target to preprocess a source file
engines/toy_tapered.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/engines/toy_tapered.cpp.i
.PHONY : engines/toy_tapered.cpp.i

engines/toy_tapered.s: engines/toy_tapered.cpp.s
.PHONY : engines/toy_tapered.s

# target to generate assembly for a file
engines/toy_tapered.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/engines/toy_tapered.cpp.s
.PHONY : engines/toy_tapered.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/main.cpp.s
.PHONY : main.cpp.s

threadpool.o: threadpool.cpp.o
.PHONY : threadpool.o

# target to build an object file
threadpool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/threadpool.cpp.o
.PHONY : threadpool.cpp.o

threadpool.i: threadpool.cpp.i
.PHONY : threadpool.i

# target to preprocess a source file
threadpool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/threadpool.cpp.i
.PHONY : threadpool.cpp.i

threadpool.s: threadpool.cpp.s
.PHONY : threadpool.s

# target to generate assembly for a file
threadpool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/threadpool.cpp.s
.PHONY : threadpool.cpp.s

tuner.o: tuner.cpp.o
.PHONY : tuner.o

# target to build an object file
tuner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/tuner.cpp.o
.PHONY : tuner.cpp.o

tuner.i: tuner.cpp.i
.PHONY : tuner.i

# target to preprocess a source file
tuner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/tuner.cpp.i
.PHONY : tuner.cpp.i

tuner.s: tuner.cpp.s
.PHONY : tuner.s

# target to generate assembly for a file
tuner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuner.dir/build.make CMakeFiles/tuner.dir/tuner.cpp.s
.PHONY : tuner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tuner"
	@echo "... engines/rice.o"
	@echo "... engines/rice.i"
	@echo "... engines/rice.s"
	@echo "... engines/toy.o"
	@echo "... engines/toy.i"
	@echo "... engines/toy.s"
	@echo "... engines/toy_tapered.o"
	@echo "... engines/toy_tapered.i"
	@echo "... engines/toy_tapered.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... threadpool.o"
	@echo "... threadpool.i"
	@echo "... threadpool.s"
	@echo "... tuner.o"
	@echo "... tuner.i"
	@echo "... tuner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

